language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

script:
  - cargo build --verbose
  - cargo build --all-features --verbose
  - cargo test --all-features --verbose
  - cargo doc --all-features --verbose
